# coding: utf-8
"""
资源包生成 API 模块
"""
from flask import Blueprint, jsonify, request, send_file
import os
import json
import zipfile
import shutil

resourcepack_bp = Blueprint('resourcepack', __name__)


@resourcepack_bp.route('/generate', methods=['POST'])
def generate_resourcepack():
    """生成资源包"""
    data = request.get_json()
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    work_folder = data.get('work_folder')
    pack_name = data.get('pack_name', 'Modpack-Localization-Pack')
    pack_description = data.get('pack_description', 'generated by ModpackLocalizationTools')
    game_version = data.get('game_version', '1.19')
    
    if not work_folder:
        return jsonify({'error': 'Work folder is required'}), 400
    
    try:
        # 创建资源包目录结构
        resourcepack_dir = os.path.join(work_folder, 'resourcepacks_temp')
        assets_dir = os.path.join(resourcepack_dir, 'assets')
        
        # 清理旧目录
        if os.path.exists(resourcepack_dir):
            shutil.rmtree(resourcepack_dir)
        
        os.makedirs(resourcepack_dir, exist_ok=True)
        
        # TODO: 实现资源包生成逻辑
        # 1. 复制语言文件到 assets 目录
        # 2. 创建 pack.mcmeta 文件
        # 3. 创建 pack.png 图标
        # 4. 压缩为 zip 文件
        
        # 创建 pack.mcmeta
        pack_format_map = {
            '1': 1, '2': 1, '3': 2, '4': 4, '5': 5, '6': 6,
            '7': 7, '8': 8, '9': 9, '11': 10, '12': 11,
            '13': 12, '14': 13, '15': 15
        }
        pack_format = pack_format_map.get(game_version, 15)
        
        mcmeta = {
            'pack': {
                'pack_format': pack_format,
                'description': pack_description
            }
        }
        
        mcmeta_path = os.path.join(resourcepack_dir, 'pack.mcmeta')
        with open(mcmeta_path, 'w', encoding='utf-8') as f:
            json.dump(mcmeta, f, indent=4, ensure_ascii=False)
        
        # 压缩为 zip
        output_path = os.path.join(work_folder, f'{pack_name}.zip')
        with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files in os.walk(resourcepack_dir):
                for file in files:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, resourcepack_dir)
                    zipf.write(file_path, arcname)
        
        # 清理临时目录
        shutil.rmtree(resourcepack_dir)
        
        return jsonify({
            'success': True,
            'file_path': output_path,
            'filename': f'{pack_name}.zip'
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@resourcepack_bp.route('/download/<path:filename>', methods=['GET'])
def download_resourcepack(filename):
    """下载资源包"""
    try:
        return send_file(filename, as_attachment=True)
    except Exception as e:
        return jsonify({'error': str(e)}), 500