# coding: utf-8
"""
设置 API 模块
"""
from flask import Blueprint, jsonify, request
import os
import json

settings_bp = Blueprint('settings', __name__)

CONFIG_FILE = os.path.join(os.path.dirname(__file__), '..', 'config', 'config.json')


@settings_bp.route('/get', methods=['GET'])
def get_settings():
    """获取设置"""
    try:
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                config = json.load(f)
        else:
            config = {
                'workFolder': 'work',
                'cacheFolder': 'cache',
                'translateApi': 'baidu',
                'theme': 'dark',
                'dpiScale': 'Auto',
                'checkUpdateAtStartUp': True,
                'keepOriginal': False,
                'lowVersionLangFormat': False,
                'appKey': '',
                'appSecret': '',
                'openaiUrl': 'https://api.openai.com/v1',
                'modelName': 'gpt-3.5-turbo',
                'orgId': '',
                'secretKey': '',
                'gameVersion': '15',
                'metaName': 'Modpack-Localization-Pack',
                'metaDesc': 'generated by ModpackLocalizationTools'
            }
        return jsonify({'success': True, 'config': config})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@settings_bp.route('/save', methods=['POST'])
def save_settings():
    """保存设置"""
    data = request.get_json()
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    try:
        config_dir = os.path.dirname(CONFIG_FILE)
        os.makedirs(config_dir, exist_ok=True)
        with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@settings_bp.route('/reset', methods=['POST'])
def reset_settings():
    """重置设置为默认值"""
    try:
        if os.path.exists(CONFIG_FILE):
            os.remove(CONFIG_FILE)
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'error': str(e)}), 500