/**
 * Pinia Store 入口
 */
import { defineStore } from 'pinia'

/**
 * 应用状态 Store
 */
export const useAppStore = defineStore('app', {
  state: () => ({
    version: '2.0.0',
    title: '整合包本地化工具',
  }),
  actions: {
    setVersion(version) {
      this.version = version
    },
  },
})

/**
 * 设置状态 Store
 */
export const useSettingsStore = defineStore('settings', {
  state: () => ({
    workFolder: 'work',
    cacheFolder: 'cache',
    translateApi: 'baidu',
    theme: 'dark',
    dpiScale: 'Auto',
    checkUpdateAtStartUp: true,
    keepOriginal: false,
    lowVersionLangFormat: false,
    appKey: '',
    appSecret: '',
    openaiUrl: 'https://api.openai.com/v1',
    modelName: 'gpt-3.5-turbo',
    orgId: '',
    secretKey: '',
    gameVersion: '15',
    metaName: 'Modpack-Localization-Pack',
    metaDesc: 'generated by ModpackLocalizationTools',
  }),
  actions: {
    updateSettings(settings) {
      Object.assign(this, settings)
    },
    async loadSettings() {
      try {
        // 从 API 加载设置
        // const response = await api.settings.get()
        // this.updateSettings(response.config)
      } catch (e) {
        console.error('Failed to load settings:', e)
      }
    },
    async saveSettings() {
      try {
        // 保存设置到 API
        // await api.settings.save(this.$state)
      } catch (e) {
        console.error('Failed to save settings:', e)
      }
    },
  },
})

/**
 * 翻译状态 Store
 */
export const useTranslationStore = defineStore('translation', {
  state: () => ({
    isTranslating: false,
    progress: 0,
    currentText: '',
    translatedText: '',
    error: null,
  }),
  actions: {
    startTranslation() {
      this.isTranslating = true
      this.progress = 0
      this.error = null
    },
    updateProgress(progress, currentText = '') {
      this.progress = progress
      this.currentText = currentText
    },
    finishTranslation(translatedText) {
      this.isTranslating = false
      this.progress = 100
      this.translatedText = translatedText
    },
    handleError(error) {
      this.isTranslating = false
      this.error = error
    },
    reset() {
      this.isTranslating = false
      this.progress = 0
      this.currentText = ''
      this.translatedText = ''
      this.error = null
    },
  },
})

export default {
  useAppStore,
  useSettingsStore,
  useTranslationStore,
}